title: "Gonzalo Saldías, PhD"
description: "Coastal Physical Oceanography at the Department of Physics, University of Bio-Bio, Concepción, Chile"
permalink: //
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "Home.md", title: Home, icon: home}
  - {file: "Research.md", title: Research}
  - {file: "Publications.md", title: Publications}
  - {file: "People.md", title: People}
  - {file: "CV.pdf", title: CV}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:gsaldias@ubiobio.cl"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/GonzaloSaldiasY"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/gonzalo-saldias/"}
  - {title: ResearchGate, icon: researchgate, url: "https://www.researchgate.net/profile/Gonzalo-Saldias"}
  - {title: Scholar Google, icon: graduation-cap, url: "https://scholar.google.com/citations?hl=en&user=of2oGYwAAAAJ&view_op=list_works&sortby=pubdate"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
- jekyll-feed
